function f_out = GRF_Constraint_Sym(Tx,Ty,Tz,X,Y)
%GRF_CONSTRAINT_SYM
%    F_OUT = GRF_CONSTRAINT_SYM(TX,TY,TZ,X,Y)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    01-Sep-2017 16:29:57

% Convert residual moment to world frame

t2 = conj(X);
t3 = conj(Y);
t4 = cos(t3);
t5 = sin(t2);
t6 = conj(Tx);
t7 = 1.0./t4;
t8 = cos(t2);
t9 = conj(Tz);
t10 = sin(t3);
t11 = conj(Ty);
f_out = [t6;t7.*(-t5.*t9+t5.*t6.*t10+t4.*t8.*t11);t7.*(t8.*t9+t4.*t5.*t11-t6.*t8.*t10)];
