%% A_provagamba compila funzione mex
% IN(1) - cartella del file
% IN(2) - nome file
function []=compilamex(varargin)
function_dir=varargin{1};
function_name=varargin{2};
if length(varargin)>2
    opensim_dir=varargin{3};
else
    opensim_dir = 'C:\OpenSim33';
end
cpp_file=[function_dir,'\',function_name];

fprintf('Compiling MexfastID function ... \n');

mex(['-I',opensim_dir],...
    ['-I',opensim_dir,'\bin'],...
    ['-I',opensim_dir,'\sdk\include'],...
    ['-I',opensim_dir,'\sdk\include\SimTK\include'],...
    ['-I',opensim_dir,'\sdk\include\opensim\common'],...
    ['-L',opensim_dir,'\sdk\lib'],...
    '-llibblas.lib',...
    '-lliblapack.lib',...
    '-lOpenSim_SimTKcommon.lib',...
    '-lOpenSim_SimTKmath.lib',...
    '-lOpenSim_SimTKsimbody.lib',...
    '-losimActuators.lib',...
    '-losimAnalyses.lib',...
    '-losimCommon.lib',...
    '-losimJavaJNI.lib',...
    '-losimLepton.lib',...
    '-losimSimmFileWriter.lib',...
    '-losimSimulation.lib',...
    '-losimTools.lib',...
    '-lpthreadVC2_x64.lib',...
    cpp_file);
